In [1]:
import pandas as pd

In [2]:
populacao_mundial = pd.read_csv('populacao_mundial.csv')

In [3]:
populacao_mundial.shape

(233, 12)

In [4]:
populacao_mundial.head()

,Rank,Country,Population_2026,Yearly_Change,Net_Change,Density_per_km2,Land_Area_km2,Migrants_Net,Fertility_Rate,Median_Age,Urban_Population_pct,World_Share_pct
0,1,India,1476625576,0.87,12760051.0,497,2973190,-440456.0,1.93,29.2,37.6,17.79
1,2,China,1412914089,-0.22,-3182005.0,150,9388211,-232107.0,1.03,40.6,68.7,17.02
2,3,United States,349035494,0.51,1759687.0,38,9147420,1177848.0,1.63,38.7,83.1,4.20
3,4,Indonesia,287886782,0.76,2165546.0,159,1811570,-39472.0,2.08,30.7,60.3,3.47
4,5,Pakistan,259299791,1.60,4080237.0,336,770880,-1144738.0,3.44,20.8,34.7,3.12

In [5]:
populacao_mundial.tail()

,Rank,Country,Population_2026,Yearly_Change,Net_Change,Density_per_km2,Land_Area_km2,Migrants_Net,Fertility_Rate,Median_Age,Urban_Population_pct,World_Share_pct
228,229,Montserrat,4328,-0.71,-31.0,43,100,-10.0,1.45,41.8,11.7,0.000052
229,230,Falkland Islands,3465,-0.12,-4.0,0,12170,-16.0,1.69,43.4,68.4,0.000042
230,231,Tokelau,2691,3.18,83.0,269,10,43.0,2.54,27.6,0.0,0.000032
231,232,Niue,1822,0.05,1.0,7,260,2.0,2.44,35.1,45.2,0.000022
232,233,Holy See,506,1.00,5.0,1265,0,13.0,1.00,56.2,0.0,0.000006

In [6]:
populacao_mundial.isnull().sum()

Rank                    0
Country                 0
Population_2026         0
Yearly_Change           0
Net_Change              0
Density_per_km2         0
Land_Area_km2           0
Migrants_Net            0
Fertility_Rate          0
Median_Age              0
Urban_Population_pct    0
World_Share_pct         0
dtype: int64

In [7]:
populacao_mundial.dropna(inplace=True)

In [8]:
populacao_mundial.nunique()

Rank                    233
Country                 233
Population_2026         233
Yearly_Change           175
Net_Change              232
Density_per_km2         171
Land_Area_km2           224
Migrants_Net            228
Fertility_Rate          161
Median_Age              169
Urban_Population_pct    190
World_Share_pct         165
dtype: int64

In [9]:
populacao_mundial.dtypes

Rank                      int64
Country                  object
Population_2026           int64
Yearly_Change           float64
Net_Change              float64
Density_per_km2           int64
Land_Area_km2             int64
Migrants_Net            float64
Fertility_Rate          float64
Median_Age              float64
Urban_Population_pct    float64
World_Share_pct         float64
dtype: object

In [10]:
populacao_mundial.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Rank                  233 non-null    int64
 1   Country               233 non-null    object
 2   Population_2026       233 non-null    int64
 3   Yearly_Change         233 non-null    float64
 4   Net_Change            233 non-null    float64
 5   Density_per_km2       233 non-null    int64
 6   Land_Area_km2         233 non-null    int64
 7   Migrants_Net          233 non-null    float64
 8   Fertility_Rate        233 non-null    float64
 9   Median_Age            233 non-null    float64
 10  Urban_Population_pct  233 non-null    float64
 11  World_Share_pct       233 non-null    float64
dtypes: float64(7), int64(4), object(1)
memory usage: 22.0+ KB

In [11]:
populacao_mundial.describe()

,Rank,Population_2026,Yearly_Change,Net_Change,Density_per_km2,Land_Area_km2,Migrants_Net,Fertility_Rate,Median_Age,Urban_Population_pct,World_Share_pct
count,233.000000,2.330000e+02,233.000000,2.330000e+02,233.000000,2.330000e+02,2.330000e+02,233.000000,233.000000,233.000000,233.000000
mean,117.000000,3.561725e+07,0.836009,2.964517e+05,489.090129,5.583427e+05,6.718884e+01,2.269957,32.067382,55.100000,0.429011
std,67.405489,1.397550e+08,1.204607,1.068382e+06,2408.108135,1.694270e+06,1.320280e+05,1.115550,10.105033,28.122878,1.683488
min,1.000000,5.060000e+02,-3.330000,-3.182005e+06,0.000000,0.000000e+00,-1.144738e+06,0.000000,0.000000,0.000000,0.000006
25%,59.000000,4.697750e+05,-0.050000,-4.700000e+01,39.000000,2.830000e+03,-7.971000e+03,1.470000,23.000000,35.500000,0.005700
50%,117.000000,5.853949e+06,0.770000,1.840600e+04,100.000000,8.220000e+04,-2.490000e+02,1.900000,33.300000,59.700000,0.071000
75%,175.000000,2.460170e+07,1.780000,2.286820e+05,255.000000,4.103400e+05,2.157000e+03,2.920000,40.200000,78.900000,0.300000
max,233.000000,1.476626e+09,3.370000,1.276005e+07,25562.000000,1.637687e+07,1.177848e+06,5.830000,56.200000,99.600000,17.790000

In [12]:
idade_media_mundo = populacao_mundial['Median_Age'].mean()
print(f'Idade média mundial: {idade_media_mundo:.2f} anos')

Idade média mundial: 32.07 anos

In [13]:
populacao_mundial['Median_Age'].describe()

count    233.000000
mean      32.067382
std       10.105033
min        0.000000
25%       23.000000
50%       33.300000
75%       40.200000
max       56.200000
Name: Median_Age, dtype: float64

In [14]:
# 1 -Top 10 países mais populosos?  

print(populacao_mundial.nlargest(10, 'Population_2026')[['Country', 'Population_2026']])

         Country  Population_2026
0          India       1476625576
1          China       1412914089
2  United States        349035494
3      Indonesia        287886782
4       Pakistan        259299791
5        Nigeria        242431832
6         Brazil        213562666
7     Bangladesh        177818044
8         Russia        143394458
9       Ethiopia        138902185

In [15]:
# 2 - Quais países têm crescimento negativo?

print(populacao_mundial[populacao_mundial['Yearly_Change'] < 0][['Country', 'Yearly_Change']].sort_values('Yearly_Change'))

                      Country  Yearly_Change
216          Marshall Islands          -3.33
221              Cook Islands          -3.29
209            American Samoa          -1.54
211  Northern Mariana Islands          -1.44
225                    Tuvalu          -1.37
..                        ...            ...
199               Isle of Man          -0.07
133                   Uruguay          -0.06
130                   Georgia          -0.05
121                   Finland          -0.03
188                   Curaçao          -0.03

[61 rows x 2 columns]

In [16]:
# 3 - Qual a média de fertilidade por faixa de urbanização?

populacao_mundial['faixa_urbana'] = pd.cut(populacao_mundial['Urban_Population_pct'], bins=[0, 30, 50, 70, 100])
print(populacao_mundial.groupby('faixa_urbana')['Fertility_Rate'].mean())

faixa_urbana
(0, 30]      3.007391
(30, 50]     3.072857
(50, 70]     2.203396
(70, 100]    1.808000
Name: Fertility_Rate, dtype: float64

C:\Users\Usuario\AppData\Local\Temp\ipykernel_20036\4265111976.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(populacao_mundial.groupby('faixa_urbana')['Fertility_Rate'].mean())

In [17]:
# 4 - Top 10 países mais densos?

print(populacao_mundial.nlargest(10, 'Density_per_km2')[['Country', 'Density_per_km2']])

          Country  Density_per_km2
215        Monaco            25562
166         Macao            24106
114     Singapore             8437
106     Hong Kong             7027
212     Gibraltar             4087
152       Bahrain             2205
172      Maldives             1772
171         Malta             1716
7      Bangladesh             1366
210  Sint Maarten             1307

In [18]:
# 5 - Quais países mais recebem e emitem migrantes?

print(populacao_mundial.nlargest(5, 'Migrants_Net')[['Country', 'Migrants_Net']])
print(populacao_mundial.nsmallest(5, 'Migrants_Net')[['Country', 'Migrants_Net']])

           Country  Migrants_Net
2    United States     1177848.0
21  United Kingdom      364099.0
8           Russia      324924.0
56           Syria      305822.0
37          Canada      291403.0
       Country  Migrants_Net
4     Pakistan    -1144738.0
0        India     -440456.0
7   Bangladesh     -371398.0
51       Nepal     -292014.0
1        China     -232107.0